## INTRODUCTION TO TORCH

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
else:
  print("NO GPU")

Tesla T4


In [ ]:
#declaring the empty tensor
torch.empty(2,3)
# 2 rows 3 cols

tensor([[1.5766e-19, 1.0256e-08, 2.5637e-09],
        [3.0613e+12, 6.9369e-07, 4.1031e-08]])

In [ ]:
#declaring the tensor with zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#declaring the tensor using ones
t=torch.ones(2,3)

In [ ]:
#checking the type of tensor
type(t)


torch.Tensor

In [ ]:
#declaring the tensor using rand
torch.rand(2,3)

tensor([[0.8591, 0.1815, 0.7579],
        [0.9119, 0.1575, 0.4464]])

In [ ]:
#using seed in rand to reproduce the results
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#now declaring the tensor with the values
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

# Shape Of Tensor

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

# Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
#change the data type of the tensor if compatible
torch.tensor([[1,2,3]],dtype=torch.float64)

tensor([[1., 2., 3.]], dtype=torch.float64)

In [ ]:
torch.tensor([[1.0,2.0,3.0]],dtype=torch.int64)

tensor([[1, 2, 3]])

In [ ]:
#using to() to change the dtype
x=torch.tensor([[1.0,2.0,3.0]])
x.to(torch.int64)

tensor([[1, 2, 3]])

# Mathematical Operations On Tensor

In [ ]:
y=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
#addition
y+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
#subtraction
y-1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
#multiplication
y*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
#division
y/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [ ]:
#int division
y//2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [ ]:
#power
y**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

# Elementwise Operations

In [ ]:
x1=torch.rand(3,3)
x2=torch.rand(3,3)

In [ ]:
x1

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])

In [ ]:
x2

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])

In [ ]:
#addition
x1+x2

tensor([[1.3755, 0.7993, 0.6571],
        [1.1472, 0.5977, 1.2020],
        [1.2738, 1.5041, 1.2806]])

In [ ]:
#subtraction
x1-x2

tensor([[-0.0802, -0.1132, -0.0206],
        [-0.0951, -0.5084, -0.1773],
        [ 0.5363, -0.3064, -0.3906]])

In [ ]:
#multiplication
x1*x2

tensor([[0.4714, 0.1565, 0.1078],
        [0.3268, 0.0247, 0.3533],
        [0.3337, 0.5421, 0.3718]])

In [ ]:
#division
x1/x2

tensor([[0.8898, 0.7518, 0.9391],
        [0.8470, 0.0808, 0.7430],
        [2.4545, 0.6615, 0.5326]])

In [ ]:
#int division
x1//x2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [2., 0., 0.]])

In [ ]:
c=torch.tensor([[1,-2,-3]])
c

tensor([[ 1, -2, -3]])

In [ ]:
#abs
torch.abs(c)

tensor([[1, 2, 3]])

In [ ]:
#negative
torch.neg(c)

tensor([[-1,  2,  3]])

In [ ]:
#round
a=torch.tensor([[2.4,5.6,6.7]])
torch.round(a)


tensor([[2., 6., 7.]])

In [ ]:
#ceil
torch.ceil(a)

tensor([[3., 6., 7.]])

In [ ]:
#floor
torch.floor(a)

tensor([[2., 5., 6.]])

In [ ]:
#clamp
d=torch.tensor([[2.3,4.5,5.6]])
torch.clamp(d,min=3,max=5)

tensor([[3.0000, 4.5000, 5.0000]])

# Tensor Reduction

In [ ]:
t=torch.randint(size=(2,3),low=0,high=10)
t

tensor([[7, 2, 6],
        [7, 7, 4]])

In [ ]:
#summing all the values in tensor
torch.sum(t)

tensor(33)

In [ ]:
#summing the values column wise
torch.sum(t,dim=0)

tensor([14,  9, 10])

In [ ]:
#summing the values row wise
torch.sum(t,dim=1)

tensor([15, 18])

In [ ]:
#getting the mean of all values in the tensor
torch.mean(t.float())

tensor(5.5000)

In [ ]:
#getting the mean along column
torch.mean(t.float(),dim=0)

tensor([7.0000, 4.5000, 5.0000])

In [ ]:
#getting the mean along rows
torch.mean(t.float(),dim=1)

tensor([5., 6.])

In [ ]:
#getting the median of all values in the tensor
torch.median(t)

tensor(6)

In [ ]:
# min
torch.min(t)

tensor(2)

In [ ]:
#max
torch.max(t)

tensor(7.)

In [ ]:
#standard deviation
torch.std(t.float())

tensor(2.0736)

In [ ]:
#variance
torch.var(t.float())

tensor(4.3000)

In [ ]:
#getting the index of the max element in the tensor ".argmax()" , (first apperance)
torch.argmax(t)

tensor(0)

In [ ]:
#getting the index of the min element in the tensor ".argmin()" ,(first appearance)
torch.argmin(t)

tensor(1)

# Matrix Operations

In [ ]:
v=torch.randint(size=(3,3),low=1,high=9)
w=torch.randint(size=(3,3),low=1,high=9)
print(v)
print(w)

tensor([[6, 7, 7],
        [7, 6, 3],
        [8, 1, 1]])
tensor([[8, 8, 8],
        [1, 8, 7],
        [8, 7, 4]])


In [ ]:
#matrix multiplication
torch.matmul(v,w)

tensor([[111, 153, 125],
        [ 86, 125, 110],
        [ 73,  79,  75]])

In [ ]:
#dot products for vectors
v1=torch.tensor([1,2,3])
v2=torch.tensor([2,3,4])

torch.dot(v1,v2)

tensor(20)

In [ ]:
#transpose
m=torch.tensor([[1,2,3],[4,5,6]])
print(m)
torch.transpose(m,0,1) #where 0 represents cols and 1 rep. rows i.e interchanging cols with rows

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
#determinant
r=torch.tensor([[1,2],[2,3]])
torch.det(r.float())

tensor(-1.)

In [ ]:
#inverse
torch.inverse(r.float())

tensor([[-3.,  2.],
        [ 2., -1.]])

# Special Functions

In [ ]:
m=torch.randint(size=(3,3),low=2,high=9)
m

tensor([[3, 5, 8],
        [8, 5, 2],
        [3, 7, 7]])

In [ ]:
#log /ln
torch.log(m)

tensor([[1.0986, 1.6094, 2.0794],
        [2.0794, 1.6094, 0.6931],
        [1.0986, 1.9459, 1.9459]])

In [ ]:
#exponent
torch.exp(m)

tensor([[  20.0855,  148.4132, 2980.9580],
        [2980.9580,  148.4132,    7.3891],
        [  20.0855, 1096.6332, 1096.6332]])

In [ ]:
#sqrt
torch.sqrt(m)

tensor([[1.7321, 2.2361, 2.8284],
        [2.8284, 2.2361, 1.4142],
        [1.7321, 2.6458, 2.6458]])

In [ ]:
#sigmoid: maps any number in between 0 and 1
torch.sigmoid(m)

tensor([[0.9526, 0.9933, 0.9997],
        [0.9997, 0.9933, 0.8808],
        [0.9526, 0.9991, 0.9991]])

In [ ]:
#relu: if number is greater than or equal to zero then the output is number itself but if number is lesser than zero then the output is zero
torch.relu(m)

tensor([[3, 5, 8],
        [8, 5, 2],
        [3, 7, 7]])

In [ ]:
#softmax: calculates the probability for each number in an array
torch.softmax(m.float(),dim=0) #column wise, but same for row wise just dim=1

tensor([[0.0066, 0.1065, 0.7297],
        [0.9867, 0.1065, 0.0018],
        [0.0066, 0.7870, 0.2685]])

# Inplace Operators

In [ ]:
#add ,saves storage
p=torch.rand(size=(2,3))
q=torch.rand(size=(2,3))
print(p)
print(q)


tensor([[0.6873, 0.5642, 0.7310],
        [0.3332, 0.2201, 0.2693]])
tensor([[0.9179, 0.1644, 0.3592],
        [0.5537, 0.9799, 0.8186]])


In [ ]:
p.add_(q) #the results of addition is stored in p instead of assigning new memory
p

tensor([[1.6052, 0.7286, 1.0902],
        [0.8870, 1.2000, 1.0879]])

In [ ]:
#same for .relu()
p.relu_()

tensor([[1.6052, 0.7286, 1.0902],
        [0.8870, 1.2000, 1.0879]])

# Copying The Variable

In [ ]:
"""usually copying the variable just adds a pointer to the same memory location, hence changes made in the original also gets reflected in the copy, in some cases it is not desirable"""
a=torch.rand(size=(2,3))
print("a",a)
b=a #copying the variable a into b
print("b",b)

#updating a tensor
a[0][0]=1
print("updated a",a)

#but b also gets updated
print("copy b",b)

#to avoid this
c=torch.rand(size=(2,3))
d=c.clone()

print("c",c)
print("d",d)

#update c
c[0][0]=1
print("updated c",c)

#unchaged d
print(d)

a tensor([[0.7163, 0.4238, 0.8232],
        [0.3789, 0.9856, 0.7857]])
b tensor([[0.7163, 0.4238, 0.8232],
        [0.3789, 0.9856, 0.7857]])
updated a tensor([[1.0000, 0.4238, 0.8232],
        [0.3789, 0.9856, 0.7857]])
copy b tensor([[1.0000, 0.4238, 0.8232],
        [0.3789, 0.9856, 0.7857]])
c tensor([[0.3936, 0.3471, 0.4599],
        [0.3147, 0.2448, 0.7050]])
d tensor([[0.3936, 0.3471, 0.4599],
        [0.3147, 0.2448, 0.7050]])
updated c tensor([[1.0000, 0.3471, 0.4599],
        [0.3147, 0.2448, 0.7050]])
tensor([[0.3936, 0.3471, 0.4599],
        [0.3147, 0.2448, 0.7050]])


# Comapring the tensor execution timing for cpu and gpu

In [ ]:
import time
size=10000
cpu_mat1=torch.rand((size,size))
cpu_mat2=torch.rand((size,size))

start_time_cpu=time.time()
result_cpu=torch.matmul(cpu_mat1,cpu_mat2)
cpu_time=time.time()-start_time_cpu

gpu_mat1=cpu_mat1.to("cuda")
gpu_mat2=cpu_mat2.to("cuda")

start_time_gpu=time.time()
result_gpu=torch.matmul(gpu_mat1,gpu_mat2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time_gpu

print("cpu time: ",cpu_time)
print("gpu time: ",gpu_time)

cpu time:  14.253764629364014
gpu time:  0.5626919269561768


In [ ]:
#time gain
print(cpu_time/gpu_time)

25.331382851835578


# Reshaping The Tensors

In [ ]:
t1=torch.ones(4,4)
t1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape  the product of the dimensions should be same i.e 4x4 =2x2x2x2
t1.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten converting the nD tensor to vector i.e 1D
t1.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])