<a href="https://colab.research.google.com/github/anmollate/DL/blob/main/SimplePipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace= True)

In [ ]:
#train test split
x_train, x_test, y_train, y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

In [ ]:
#scaling
scaler=StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-1.66839862, -0.57686166, -1.64666322, ..., -1.33670202,
         0.33437924, -0.53537402],
       [ 1.8303042 ,  0.37395265,  1.90151634, ...,  1.57421844,
         0.28849196, -0.44811533],
       [-0.25124556, -0.81811305, -0.31295326, ..., -1.34655077,
        -0.40965022, -0.00309601],
       ...,
       [-1.20082874, -0.85122599, -1.18134847, ..., -0.72669522,
        -0.6538361 ,  0.44628625],
       [ 0.46526068, -1.89191827,  0.45899938, ...,  0.50316714,
        -0.56370037, -0.11435084],
       [-1.01872854,  0.00261473, -0.99959133, ..., -1.23836843,
        -0.12285473, -0.45738656]])

In [ ]:
y_train

46     B
535    M
306    B
337    M
63     B
      ..
422    B
386    B
524    B
484    B
104    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
#encoding the values in y column
encoder = LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
#converting the numpy arrays to tensors
x_train_tensor=torch.from_numpy(x_train)
y_train_tensor=torch.from_numpy(y_train)
x_test_tensor=torch.from_numpy(x_test)
y_test_tensor=torch.from_numpy(y_test)


In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

# Defining The Model

In [ ]:
class mysimplenn():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [ ]:
learning_rate=0.1
epochs=25


In [ ]:
#create model
model=mysimplenn(x_train_tensor)
model.weights

# define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(x_train_tensor)
  # print(y_pred)

  #loss
  loss=model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()


  # w and b updation
  with torch.no_grad():
    model.weights-=learning_rate * model.weights.grad
    model.bias-=learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.523283408586694
Epoch: 2, Loss: 3.3892966301229155
Epoch: 3, Loss: 3.242425790738285
Epoch: 4, Loss: 3.0943035122825058
Epoch: 5, Loss: 2.9441266693574764
Epoch: 6, Loss: 2.7912507016769577
Epoch: 7, Loss: 2.634481751516679
Epoch: 8, Loss: 2.467962729411159
Epoch: 9, Loss: 2.303657863334866
Epoch: 10, Loss: 2.13964207011394
Epoch: 11, Loss: 1.9765226891102858
Epoch: 12, Loss: 1.820154723676944
Epoch: 13, Loss: 1.6700535398833074
Epoch: 14, Loss: 1.5222560385711315
Epoch: 15, Loss: 1.386225371170361
Epoch: 16, Loss: 1.2653218792728547
Epoch: 17, Loss: 1.1608835190614797
Epoch: 18, Loss: 1.0735778513279082
Epoch: 19, Loss: 1.0030812742794728
Epoch: 20, Loss: 0.9479255486776298
Epoch: 21, Loss: 0.9057038418041068
Epoch: 22, Loss: 0.8736120489546843
Epoch: 23, Loss: 0.8490161781571902
Epoch: 24, Loss: 0.8297752399570916
Epoch: 25, Loss: 0.8143055734014918


In [ ]:
model.weights

tensor([[ 0.4127],
        [ 0.2497],
        [ 0.0746],
        [-0.3970],
        [ 0.2793],
        [-0.0993],
        [-0.3855],
        [-0.4976],
        [-0.2531],
        [ 0.1507],
        [ 0.3798],
        [ 0.3204],
        [ 0.5035],
        [-0.2495],
        [-0.0853],
        [ 0.2988],
        [ 0.3741],
        [-0.3911],
        [-0.0103],
        [ 0.3673],
        [-0.0475],
        [ 0.0061],
        [ 0.1009],
        [ 0.3237],
        [-0.1941],
        [ 0.1593],
        [-0.1882],
        [-0.1599],
        [-0.0381],
        [ 0.3348]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1598], dtype=torch.float64, requires_grad=True)

In [ ]:
#model Evaluation
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)
  y_pred=(y_pred>0.5).float()
  print(y_pred)

tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [ ]:
accurracy=(y_pred==y_test_tensor).float().mean()
print(f'accurracy:{accurracy.item()}')

accurracy:0.5253924131393433
